services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 --ignore-db-dir=lost+found
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  app:
    build:
      context: node
    container_name: app
    volumes:
      - ./node:/app
    tty: true
    networks:
      - node-network
    depends_on:
      - db

  nginx:
    build:
      context: nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - db
      - app

networks:
  node-network:
    driver: bridge